apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-app
  labels:
    app: mc-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mc-app
  template:
    metadata:
      labels:
        app: mc-app
    spec:
      containers:
      - name: mc-app
        image: docker-images/mc-app:3
        ports:
        - containerPort: 8080

      
---

apiVersion: v1
kind: Service
metadata:
  name: mc-app-service
spec:
   selector:
     app: mc-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
    app: mc-app
